name: sqfentity
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.

version: 1.5.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  sqfentity_gen:
    path: sqfentity_gen

dependency_overrides:
  build_runner: 2.4.15
  build_verify: 3.1.0

dev_dependencies:
  build_runner: 2.4.15
  build_verify: 3.1.0
